### ISSUE TITLE
1.0.0 checklist

### ISSUE THREAD

**Issue by ungoldman** [ungoldman/style.css#35]
- [x] improve usage, docs #33 
- [x] better link color #34 
- [x] revise heading size and weight

![](https://media.giphy.com/media/ctRT2hYFyZIIg/giphy.gif)
